// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb5ngXCwPkqfhuMsqBmAZchX-eg5TianY',
    appId: '1:488283651265:web:cbbe5192cbe813776aa840',
    messagingSenderId: '488283651265',
    projectId: 'bookstore-299b6',
    authDomain: 'bookstore-299b6.firebaseapp.com',
    storageBucket: 'bookstore-299b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5mcG2LMthu0E4vOAEjMFp8ahress2F9s',
    appId: '1:488283651265:android:4a15356576e8a2c76aa840',
    messagingSenderId: '488283651265',
    projectId: 'bookstore-299b6',
    storageBucket: 'bookstore-299b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0ih6BUd7RMi0nQFKVlQJQ84tKEEjXRtQ',
    appId: '1:488283651265:ios:bc06d579a77ae8756aa840',
    messagingSenderId: '488283651265',
    projectId: 'bookstore-299b6',
    storageBucket: 'bookstore-299b6.appspot.com',
    iosBundleId: 'com.example.bookstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0ih6BUd7RMi0nQFKVlQJQ84tKEEjXRtQ',
    appId: '1:488283651265:ios:98ec76700be033016aa840',
    messagingSenderId: '488283651265',
    projectId: 'bookstore-299b6',
    storageBucket: 'bookstore-299b6.appspot.com',
    iosBundleId: 'com.example.bookstore.RunnerTests',
  );
}
